import numpy as np


social_mice = ('social_0106_1', 'social-0914-1', 'social-0914-4', 'social-0921-2')


exclude_list = {
}

social_VR_sessions = {
    'social_0106_1': (
        {'date': '14_03_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':, 'exp_day':1},
        {'date': '14_03_2024' , 'scene': 'soical_dark_background_1', 'session':, 'scan':, 'exp_day':1},
        {'date': '14_03_2024' , 'scene': 'soical_dark_background_2', 'session':, 'scan':, 'exp_day':1},
        {'date': '14_03_2024' , 'scene': 'soical_dark_background_3', 'session':, 'scan':, 'exp_day':1}
    ),
    'social-0914-1': (
        {'date': '02_10_2024' , 'scene': 'soical_dark_background_1', 'session':, 'scan':1, 'exp_day':1},
        {'date': '02_10_2024' , 'scene': 'soical_dark_background_2', 'session':, 'scan':1, 'exp_day':1},
        {'date': '02_10_2024' , 'scene': 'soical_dark_background_3', 'session':, 'scan':1, 'exp_day':1},
        {'date': '03_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '03_10_2024' , 'scene': 'social_emptytunnel_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '03_10_2024' , 'scene': 'social_restrict_fam_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '03_10_2024' , 'scene': 'social_unrestrict_fam_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '03_10_2024' , 'scene': 'social_wheel_restrict_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':1, 'exp_day':3},
        {'date': '04_10_2024' , 'scene': 'social_restrict_fam_1', 'session':, 'scan':1, 'exp_day':3},
        {'date': '04_10_2024' , 'scene': 'social_restrict_nov_1', 'session':, 'scan':1, 'exp_day':3},
        {'date': '04_10_2024' , 'scene': 'social_unrestrict_fam_1', 'session':, 'scan':1, 'exp_day':3},
        {'date': '04_10_2024' , 'scene': 'social_unrestrict_nov_1', 'session':, 'scan':1, 'exp_day':3},
        {'date': '04_10_2024' , 'scene': 'social_wheel_restrict_1', 'session':, 'scan':1, 'exp_day':3},
        {'date': '05_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':1, 'exp_day':4},
        {'date': '05_10_2024' , 'scene': 'social_unrestrict_fam_1', 'session':, 'scan':1, 'exp_day':4},
        {'date': '05_10_2024' , 'scene': 'social_unrestrict_nov_1', 'session':, 'scan':1, 'exp_day':4},
        {'date': '06_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':1, 'exp_day':5},
        {'date': '06_10_2024' , 'scene': 'social_restrict_nov_diffsex_1', 'session':, 'scan':1, 'exp_day':5},
        # {'date': '06_10_2024' , 'scene': 'social_unrestrict_nov_1', 'session':, 'scan':, 'exp_day':5},
        {'date': '06_10_2024' , 'scene': 'social_unrestrict_nov_2', 'session':, 'scan':1, 'exp_day':5},
        {'date': '06_10_2024' , 'scene': 'social_unrestrict_nov_diffsex_1', 'session':1, 'scan':, 'exp_day':5},
        {'date': '06_10_2024' , 'scene': 'social_wheel_restrict_1', 'session':, 'scan':1, 'exp_day':5},
    ),
    'social-0914-4': (
        # {'date': '03_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':, 'exp_day':2},
        {'date': '03_10_2024' , 'scene': 'social_emptytunnel_1', 'session':, 'scan':1, 'exp_day':1},
        {'date': '03_10_2024' , 'scene': 'social_restrict_fam_1', 'session':, 'scan':1, 'exp_day':1},
        {'date': '03_10_2024' , 'scene': 'social_unrestrict_fam_1', 'session':, 'scan':1, 'exp_day':1},
        {'date': '03_10_2024' , 'scene': 'social_wheel_restrict_1', 'session':, 'scan':1, 'exp_day':1},
        {'date': '04_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'social_restrict_fam_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'social_restrict_nov_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'social_unrestrict_fam_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'social_unrestrict_nov_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'social_wheel_restrict_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '05_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':1, 'exp_day':3},
        # {'date': '05_10_2024' , 'scene': 'social_unrestrict_fam_1', 'session':, 'scan':, 'exp_day':3},
        {'date': '05_10_2024' , 'scene': 'social_unrestrict_fam_2', 'session':, 'scan':1, 'exp_day':3},
        {'date': '05_10_2024' , 'scene': 'social_unrestrict_nov_1', 'session':, 'scan':1, 'exp_day':3},
        {'date': '06_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':1, 'exp_day':4},
        {'date': '06_10_2024' , 'scene': 'social_restrict_nov_diffsex_1', 'session':, 'scan':1, 'exp_day':4},
        {'date': '06_10_2024' , 'scene': 'social_unrestrict_nov_1', 'session':, 'scan':1, 'exp_day':4},
        # {'date': '06_10_2024' , 'scene': 'social_unrestrict_nov_2', 'session':, 'scan':, 'exp_day':4},
        {'date': '06_10_2024' , 'scene': 'social_unrestrict_nov_diffsex_1', 'session':, 'scan':1, 'exp_day':4},
        {'date': '06_10_2024' , 'scene': 'social_wheel_restrict_1', 'session':, 'scan':1, 'exp_day':4},
    ),
    'social-0921-2': (
        # {'date': '03_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':, 'exp_day':2},
        {'date': '03_10_2024' , 'scene': 'social_emptytunnel_1', 'session':, 'scan':1, 'exp_day':1},
        {'date': '03_10_2024' , 'scene': 'social_restrict_fam_1', 'session':, 'scan':1, 'exp_day':1},
        {'date': '03_10_2024' , 'scene': 'social_unrestrict_fam_1', 'session':, 'scan':1, 'exp_day':1},
        {'date': '03_10_2024' , 'scene': 'social_wheel_restrict_1', 'session':, 'scan':1, 'exp_day':1},
        # {'date': '04_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'social_restrict_fam_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'social_restrict_nov_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'social_unrestrict_fam_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'social_unrestrict_nov_1', 'session':, 'scan':1, 'exp_day':2},
        {'date': '04_10_2024' , 'scene': 'social_wheel_restrict_1', 'session':, 'scan':1, 'exp_day':2},
        # {'date': '05_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':, 'exp_day':3},
        {'date': '05_10_2024' , 'scene': 'social_unrestrict_fam_1', 'session':, 'scan':1, 'exp_day':3},
        # {'date': '05_10_2024' , 'scene': 'social_unrestrict_fam_2', 'session':, 'scan':, 'exp_day':3},
        {'date': '05_10_2024' , 'scene': 'social_unrestrict_nov_1', 'session':, 'scan':1, 'exp_day':3},
        # {'date': '06_10_2024' , 'scene': 'Env1_to_Env2_fixreward_1', 'session':, 'scan':, 'exp_day':4},
        {'date': '06_10_2024' , 'scene': 'social_restrict_nov_diffsex_1', 'session':, 'scan':1, 'exp_day':4},
        {'date': '06_10_2024' , 'scene': 'social_unrestrict_nov_1', 'session':, 'scan':1, 'exp_day':4},
        # {'date': '06_10_2024' , 'scene': 'social_unrestrict_nov_2', 'session':, 'scan':, 'exp_day':4},
        {'date': '06_10_2024' , 'scene': 'social_unrestrict_nov_diffsex_1', 'session':, 'scan':1, 'exp_day':4},
        {'date': '06_10_2024' , 'scene': 'social_wheel_restrict_1', 'session':, 'scan':1, 'exp_day':4},
    )

social_SLP_sessions = {
    'social_0106_1': (
        
    )
}
        
SparseKO_sessions = {
    'SparseKO_05': (
        #{'date': '30_10_2024', 'scene': 'RunningTraining_scan', 'session': 2, 'scan': 3, 'novel_arm': -1, 'exp_day': 0},
                    {'date': '16_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 22, 'novel_arm': -1, 'exp_day': 1},
                    {'date': '17_11_2024', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 13, 'novel_arm': -1, 'exp_day': 2},
                    {'date': '18_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 10, 'novel_arm': -1, 'exp_day': 3},
                    {'date': '19_11_2024', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 16, 'novel_arm': -1, 'exp_day': 4},
                    {'date': '20_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 20, 'novel_arm': -1, 'exp_day': 5},
                    {'date': '21_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 16, 'novel_arm': -1, 'exp_day': 6},
                    {'date': '22_11_2024', 'scene': 'YMaze_LNovel_LongTimeout', 'session': 1, 'scan': 23, 'novel_arm': -1, 'exp_day': 7},
                  ),
    
    'SparseKO_02': ({'date': '16_11_2024', 'scene': 'YMaze_LNovel', 'session': 4, 'scan': 14, 'novel_arm': -1, 'exp_day': 1},
                    {'date': '17_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 25, 'novel_arm': -1, 'exp_day': 2},
                    {'date': '18_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 18, 'novel_arm': -1,  'exp_day': 3},
                    {'date': '19_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': -1, 'exp_day': 4},
                    {'date': '20_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 12, 'novel_arm': -1, 'exp_day': 5},
                    {'date': '21_11_2024', 'scene': 'YMaze_LNovel', 'session':2, 'scan': 8, 'novel_arm': -1, 'exp_day': 6},
                    {'date': '22_11_2024', 'scene': 'YMaze_LNovel_LongTimeout', 'session': 2, 'scan': 15, 'novel_arm': -1, 'exp_day': 7}
                   
                  ),
    'SparseKO_03': ({'date': '16_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 17, 'novel_arm': 1, 'exp_day': 1},
                    {'date': '17_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'exp_day': 2},
                    {'date': '18_11_2024', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 6, 'novel_arm': 1, 'exp_day': 3},
                    {'date': '19_11_2024', 'scene': 'YMaze_LNovel', 'session': 4, 'scan': 7, 'novel_arm': 1, 'exp_day': 4},
                    {'date': '20_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 16, 'novel_arm': 1, 'exp_day': 5},
                    {'date': '21_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 12, 'novel_arm': 1, 'exp_day': 6},
                    {'date': '22_11_2024', 'scene': 'YMaze_LNovel_LongTimeout', 'session': 1, 'scan': 19, 'novel_arm': 1, 'exp_day': 7},
                   
                  )
}

CTRL_behavior_sessions = {
    '4467331.1': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': -1, 'ravel_ind': 0},
                  {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 7, 'novel_arm': -1, 'ravel_ind': 1},
                  {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': -1, 'ravel_ind': 2},
                  {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': -1, 'ravel_ind': 3},
                  {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8, 'novel_arm': -1, 'ravel_ind': 4},
                  {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': -1, 'ravel_ind': 5},
                  (
                      {'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': -1,
                       'ravel_ind': 6},
                      {'date': '05_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4, 'novel_arm': -1,
                       'ravel_ind': 7},),
                  {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 2, 'scan': 1, 'novel_arm': -1,
                   'ravel_ind': 8},
                  ({'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3, 'novel_arm': -1,
                    'ravel_ind': 9},
                   {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5, 'novel_arm': -1,
                    'ravel_ind': 10}),
                  ),

    '4467331.2': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': 1, 'ravel_ind': 0},
                  {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': 1, 'ravel_ind': 1},
                  {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': 1, 'ravel_ind': 2},
                  ({'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6, 'novel_arm': 1, 'ravel_ind': 3},
                   {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 12, 'novel_arm': 1,
                    'ravel_ind': 4},),
                  {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 5},
                  {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 6},
                  ({'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 7},
                   {'date': '05_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4, 'novel_arm': 1,
                    'ravel_ind': 8},),
                  {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4, 'novel_arm': 1,
                   'ravel_ind': 9},
                  ({'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2, 'novel_arm': 1,
                    'ravel_ind': 10},
                   {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': 1,
                    'ravel_ind': 11}),
                  ),

    '4467332.1': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8, 'novel_arm': -1, 'ravel_ind': 0},
                  {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': -1, 'ravel_ind': 1},
                  {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5, 'novel_arm': -1, 'ravel_ind': 2},
                  {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6, 'novel_arm': -1, 'ravel_ind': 3},
                  {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': -1, 'ravel_ind': 4},
                  {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': -1, 'ravel_ind': 5},
                  (
                      {'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': -1,
                       'ravel_ind': 6},
                      {'date': '05_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5, 'novel_arm': -1,
                       'ravel_ind': 7},),
                  {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 1, 'novel_arm': -1,
                   'ravel_ind': 8},
                  ({'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2, 'novel_arm': -1,
                    'ravel_ind': 9},
                   {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5, 'novel_arm': -1,
                    'ravel_ind': 10}),
                  ),

    '4467332.2': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 18, 'novel_arm': 1, 'ravel_ind': 1},
                  # ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 14, 'novel_arm': 1, 'ravel_ind': 0},
                  #  {'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 18, 'novel_arm': 1, 'ravel_ind': 1}),
                  ({'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': 1, 'ravel_ind': 2},
                   {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 3, 'scan': 9, 'novel_arm': 1,
                    'ravel_ind': 3}),
                  {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': 1, 'ravel_ind': 4},
                  {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': 1, 'ravel_ind': 5},
                  {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 6},
                  {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 7},
                  ({'date': '06_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 8},
                   {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 6, 'novel_arm': 1,
                    'ravel_ind': 9},),
                  {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 2, 'scan': 2, 'novel_arm': 1,
                   'ravel_ind': 10},
                  ({'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2, 'novel_arm': 1,
                    'ravel_ind': 11},
                   {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6, 'novel_arm': 1,
                    'ravel_ind': 12}),
                  ),

    '4467333.1': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': -1, 'ravel_ind': 0},
                  {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6, 'novel_arm': -1, 'ravel_ind': 1},
                  {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': -1, 'ravel_ind': 2},
                  {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': -1, 'ravel_ind': 3},
                  {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 4, 'novel_arm': -1, 'ravel_ind': 4},
                  {'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': -1, 'ravel_ind': 5},
                  (
                      {'date': '06_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': -1,
                       'ravel_ind': 6},
                      {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5, 'novel_arm': -1,
                       'ravel_ind': 7},),
                  {'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2, 'novel_arm': -1,
                   'ravel_ind': 8},
                  ({'date': '08_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2, 'novel_arm': -1,
                    'ravel_ind': 9},
                   {'date': '08_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': -1,
                    'ravel_ind': 10}),
                  ),


    'mCherry6': ({'date': '14_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 0},
                 {'date': '15_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 1},
                 {'date': '16_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 2},
                 {'date': '17_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 3},
                 {'date': '18_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 1, 'novel_arm': 1, 'ravel_ind': 4},
                 {'date': '19_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5, 'novel_arm': 1, 'ravel_ind': 5},
                ({'date': '20_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 1, 'novel_arm': 1, 'ravel_ind': 6},
                 {'date': '20_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 7}),
                 {'date': '21_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 8},
                ({'date': '22_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 1, 'novel_arm': 1, 'ravel_ind': 9},
                 {'date': '22_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 10}),
                ),

    'mCherry7': ({'date': '14_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': -1, 'ravel_ind': 0},
                 {'date': '15_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': -1, 'ravel_ind': 1},
                 {'date': '16_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': -1, 'ravel_ind': 2},
                 {'date': '17_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': -1, 'ravel_ind': 3},
                 {'date': '18_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': -1, 'ravel_ind': 4},
                 {'date': '19_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': -1, 'ravel_ind': 5},
                ({'date': '20_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': -1, 'ravel_ind': 6},
                 {'date': '20_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5, 'novel_arm': -1, 'ravel_ind': 7},),
                 {'date': '21_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4, 'novel_arm': -1, 'ravel_ind': 8},
                ({'date': '22_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3, 'novel_arm': -1, 'ravel_ind': 9},
                 {'date': '22_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6, 'novel_arm': -1, 'ravel_ind': 10},),
                ),

    'mCherry8': ({'date': '14_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 0},
                 {'date': '15_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 1},
                 {'date': '16_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 2},
                 {'date': '17_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 3},
                 {'date': '18_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 4},
                 {'date': '20_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 5},
                ({'date': '21_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 1, 'novel_arm': 1, 'ravel_ind': 6},
                 {'date': '21_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 7}),
                 {'date': '22_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 8},
                ({'date': '22_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 2, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 9},
                 {'date': '22_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': 1, 'ravel_ind': 10}),
                ),

    'mCherry9': ({'date': '15_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 0},
                 {'date': '16_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 1},
                 {'date': '17_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 2},
                 {'date': '19_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 3},
                 {'date': '20_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3, 'novel_arm': 1, 'ravel_ind': 4},
                 {'date': '21_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 5},
                ({'date': '22_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 6},
                 {'date': '22_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4, 'novel_arm': 1, 'ravel_ind': 7}),
                 {'date': '22_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 2, 'scan': 4, 'novel_arm': 1, 'ravel_ind': 8},
                ({'date': '23_10_2021', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2, 'novel_arm': 1, 'ravel_ind': 9},
                 {'date': '23_10_2021', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': 1, 'ravel_ind': 10}),
                ),




}

SparseKO_behavior_sessions = {
    'SparseKO_05': (
        # {'date': '30_10_2024', 'scene': 'RunningTraining_scan', 'session': 2, 'scan': 3, 'novel_arm': -1, 'exp_day': 0},
                    {'date': '16_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 22, 'novel_arm': -1, 'exp_day': 1},
                    {'date': '17_11_2024', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 13, 'novel_arm': -1, 'exp_day': 2},
                    {'date': '18_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 10, 'novel_arm': -1, 'exp_day': 3},
                    {'date': '19_11_2024', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 16, 'novel_arm': -1, 'exp_day': 4},
                    {'date': '20_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 20, 'novel_arm': -1, 'exp_day': 5},
                    {'date': '21_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 16, 'novel_arm': -1, 'exp_day': 6},
                    {'date': '22_11_2024', 'scene': 'YMaze_LNovel_LongTimeout', 'session': 1, 'scan': 23, 'novel_arm': -1, 'exp_day': 7},
                  ),
    
    'SparseKO_02': ({'date': '16_11_2024', 'scene': 'YMaze_LNovel', 'session': 4, 'scan': 14, 'novel_arm': -1, 'exp_day': 1},
                    {'date': '17_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 25, 'novel_arm': -1, 'exp_day': 2},
                    {'date': '18_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 18, 'novel_arm': -1,  'exp_day': 3},
                    {'date': '19_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4, 'novel_arm': -1, 'exp_day': 4},
                    {'date': '20_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 12, 'novel_arm': -1, 'exp_day': 5},
                    {'date': '21_11_2024', 'scene': 'YMaze_LNovel', 'session':2, 'scan': 8, 'novel_arm': -1, 'exp_day': 6},
                    {'date': '22_11_2024', 'scene': 'YMaze_LNovel_LongTimeout', 'session': 2, 'scan': 15, 'novel_arm': -1, 'exp_day': 7}
                   
                  ),
    'SparseKO_03': ({'date': '16_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 17, 'novel_arm': 1, 'exp_day': 1},
                    {'date': '17_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2, 'novel_arm': 1, 'exp_day': 2},
                    {'date': '18_11_2024', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 6, 'novel_arm': 1, 'exp_day': 3},
                    {'date': '19_11_2024', 'scene': 'YMaze_LNovel', 'session': 4, 'scan': 7, 'novel_arm': 1, 'exp_day': 4},
                    {'date': '20_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 16, 'novel_arm': 1, 'exp_day': 5},
                    {'date': '21_11_2024', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 12, 'novel_arm': 1, 'exp_day': 6},
                    {'date': '22_11_2024', 'scene': 'YMaze_LNovel_LongTimeout', 'session': 1, 'scan': 19, 'novel_arm': 1, 'exp_day': 7},
                   
                  )
}

